language: go

go:
  - "1.12.x"

# set to true to disable default go get -t ./... because all our dependencies are already at /vendor
install: true

script:
  - go test -bench=. -cover -benchmem  ./...